### PR TITLE
Update jquery

### PR DESCRIPTION
**Pull request by mcbouslog**
- Update jQuery (to v3.3.1) and publisssh. 
- Edit noted node version.

### CODE REVIEW

**Comment by mcbouslog** [comment]
attempted to deploy to staging (https://www.wormwatchlab.org/staging/), added `--force` to publisssh part of `deploy-to-staging` script, not working.

**Comment by mcbouslog** [comment]
hmmm. if I don't update `haw`, leave it at 0.2.15, then it appears to work* (see https://www.wormwatchlab.org/staging/ and run `$().jquery` in console).

*https://www.wormwatchlab.org (which I haven't touched) wasn't and https://www.wormwatchlab.org/staging/ isn't loading a tutorial subject.

**Comment by eatyourgreens** [comment]
@mcbouslog `haw` broke at some point, because `imagemin` broke, and the latest version requires an up-to-date version of node. I've been using node 6 if I upgrade haw.

**Comment by mcbouslog** [comment]
ah good to know, thanks!

**Comment by eatyourgreens** [comment]
I think everything works fine if you already have an old version of haw installed. I've only run into problems when getting old projects up and running for the first time on a new machine, because old versions of `imagemin` no longer build on OSX.

**Pull request merged**
